[package]
name = "virs-strategy"
version = "0.1.0"
edition = "2021"

[dependencies]
virs-error = { path = "../virs-error", features = ["reqwest"] }
virs-types = { path = "../virs-types" }
virs-indicator = { path = "../virs-indicator" }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
