[package]
name = "virs-market"
version = "0.1.0"
edition = "2021"

[dependencies]
virs-type = { path = "../../core/virs-type" }
virs-exchange = { path = "../../domain/virs-exchange" }
virs-error = { path = "../../infra/virs-error" }
virs-task = { path = "../../infra/virs-task" }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }

[lints]
workspace = true
