[package]
name = "virs-market"
version = "0.1.0"
edition = "2021"

[dependencies]
virs-types = { path = "../../libs/virs-types" }
virs-ccxt = { path = "../../libs/virs-ccxt" }
virs-exchange = { path = "../../libs/virs-exchange" }
virs-error = { path = "../../libs/virs-error", features = ["sqlx"] }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }

[lints]
workspace = true
