

too-many-arguments-threshold = 10


type-complexity-threshold = 500


enum-variant-size-threshold = 200


too-large-for-stack = 200


literal-representation-threshold = 16384


cognitive-complexity-threshold = 50

