[package]
name = "virs-type"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
virs-error = { path = "../../foundation/virs-error", features = ["sqlx"] }
futures-core = { workspace = true }
sqlx = { workspace = true, optional = true }
tracing = { workspace = true }
tokio = { workspace = true }

[features]
default = ["sqlx"]
sqlx = ["dep:sqlx"]

[lints]
workspace = true
