[package]
name = "virs-config"
version = "0.1.0"
edition = "2021"

[dependencies]
virs-types = { path = "../virs-types" }
serde = { workspace = true }
serde_json = { workspace = true }
dotenvy = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
