[package]
name = "virs-position"
version = "0.1.0"
edition = "2021"

[dependencies]
virs-types = { path = "../../libs/virs-types" }
virs-error = { path = "../../libs/virs-error", features = ["sqlx"] }
virs-exchange = { path = "../../libs/virs-exchange" }
virs-task = { path = "../../libs/virs-task" }

serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
sqlx = { workspace = true }
futures-util = { workspace = true }

[lints]
workspace = true
