[package]
name = "virs-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
virs-types = { path = "../../libs/virs-types" }
virs-error = { path = "../../libs/virs-error", features = ["reqwest"] }
virs-config = { path = "../../libs/virs-config" }
virs-strategy = { path = "../../libs/virs-strategy" }
virs-market = { path = "../virs-market" }
virs-task = { path = "../../libs/virs-task" }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
reqwest = { workspace = true }
talib-rs = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
