[package]
name = "virs-ccxt"
version = "0.1.0"
edition = "2021"

[dependencies]
virs-types = { path = "../virs-types" }
virs-error = { path = "../virs-error", features = ["reqwest"] }
virs-ws = { path = "../virs-ws" }
virs-runtime = { path = "../virs-runtime" }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
rand = { workspace = true }

[lints]
workspace = true
