[package]
name = "virs-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "virs"
path = "src/main.rs"

[dependencies]
virs-trading-bot = { path = "../../crates/services/virs-trading-bot" }
virs-api = { path = "../../crates/services/virs-api" }
virs-tactical-bot = { path = "../../crates/services/virs-tactical-bot" }
virs-indicator = { path = "../../crates/libs/virs-indicator" }
virs-type = { path = "../../crates/libs/virs-type" }
virs-error = { path = "../../crates/libs/virs-error", features = ["sqlx"] }
virs-config = { path = "../../crates/libs/virs-config" }
virs-utils = { path = "../../crates/libs/virs-utils" }
virs-exchange = { path = "../../crates/libs/virs-exchange" }
virs-ccxt = { path = "../../crates/libs/virs-ccxt" }
virs-market = { path = "../../crates/services/virs-market" }
virs-position = { path = "../../crates/services/virs-position" }
virs-task = { path = "../../crates/libs/virs-task" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sqlx = { workspace = true }
axum = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }

[lints]
workspace = true
