[package]
name = "virs-exchange"
version = "0.1.0"
edition = "2021"

[dependencies]
virs-types = { path = "../virs-types" }
virs-ccxt = { path = "../virs-ccxt" }
virs-models = { path = "../virs-models" }
virs-error = { path = "../virs-error", features = ["sqlx"] }
serde = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
dashmap = { workspace = true }
tokio-stream = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
serde_json = { workspace = true }
