[package]
name = "virs-exchange"
version = "0.1.0"
edition = "2021"

[dependencies]
virs-type = { path = "../../core/virs-type" }
virs-error = { path = "../../infra/virs-error" }
serde = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
dashmap = { workspace = true }
tokio-stream = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }

[lints]
workspace = true
